#!/bin/bash
# Build Cactus XEX + ATR (sources in src/)

mkdir -p bin

# Build stamp for welcome screen (written inside src/)
STAMP=$(date +"%d.%m.%Y %H:%M")
WELCOME="Cactus b01 $STAMP"
COL=$(( (80 - ${#WELCOME}) / 2 ))
cat > src/build_stamp.asm << EOF
; Auto-generated by build.sh
msg_welcome     dta c'$WELCOME',0
msg_welcome_col = $COL
EOF

# Assemble from src/ (icl paths are relative to that directory)
(cd src && ../mads.exe cactus.asm -o:../bin/cactus.xex -l:../bin/cactus.lab -t:../bin/cactus.lst)
if [ $? -ne 0 ]; then
    echo "Build FAILED"
    exit 1
fi

echo "XEX:"
ls -la bin/cactus.xex

# Package into ATR — PicoBoot405 boots first file (CACTUS.XEX)
rm -rf bin/atr_root
mkdir -p bin/atr_root
cp bin/cactus.xex bin/atr_root/CACTUS.XEX

./dir2atr.exe -b PicoBoot405 bin/cactus.atr bin/atr_root >/dev/null 2>&1

if [ -f bin/cactus.atr ]; then
    echo "ATR:"
    ls -la bin/cactus.atr
else
    echo "ATR build FAILED"
    exit 1
fi
