#!/bin/bash
# Build script for VBXE Web Browser
# Assembler: MADS (Mad Assembler)

cd "$(dirname "$0")"

mkdir -p bin

# Generate build timestamp
STAMP=$(date +"%d.%m.%Y %H:%M")
MSG="VBXE Browser a54 $STAMP"
LEN=${#MSG}
COL=$(( (80 - LEN) / 2 ))

echo "; Auto-generated by build.sh - do not edit manually" > src/build_stamp.asm
echo "msg_welcome     dta c'$MSG',0" >> src/build_stamp.asm
echo "msg_welcome_col = $COL" >> src/build_stamp.asm

echo "Assembling VBXE Web Browser..."
./mads.exe src/browser.asm -o:bin/browser.xex -l:bin/browser.lab -t:bin/browser.lst

if [ $? -eq 0 ]; then
    echo "Build successful: bin/browser.xex"
    ls -la bin/browser.xex
else
    echo "Build FAILED!"
    exit 1
fi
